openapi: 3.0.3
info:
  title: simple-api
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /{ressource}:
    parameters:
      - name: client
        in: header
        required: true
        schema:
          type: string
      - name: ressource
        in: path
        required: true
        schema:
          type: string
    get:
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          schema:
            type: integer
      description: liste les entités de la ressources
      responses:
        200:
          description: liste d'entités
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/entity'
    post:
      description: cree une entité de la ressource
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        200:
          description: entité qui vient d'être créée
          content:
            application/json:
              schema:
                $ref: '#components/schemas/entity'
  /{ressource}/{ref}:
    parameters:
      - name: client
        in: header
        required: true
        schema:
          type: string
      - name: ressource
        in: path
        required: true
        schema:
          type: string
      - name: ref
        in: path
        required: true
        schema:
          type: string
    get:
      description: entité de la ressources correspondant à la ref
      responses:
        200:
          description: liste d'entités
          content:
            application/json:
              schema:
                $ref: '#components/schemas/entity'
    post:
      description: modifie une entité de la ressource correspondant à la ref
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        200:
          description: entité qui vient d'être modifiée
          content:
            application/json:
              schema:
                $ref: '#components/schemas/entity'
    delete:
      description: supprime une entité de la ressource correspondant à la ref
      responses:
        200:
          description: entité supprimée
  /user:
  /user/{ref}:
  /connect:
  /forgotten:
  /recover:

components:
  schemas:
    entity:
      type: object
      required:
        - ref
        - created
        - owner
      properties:
        ref:
          type: string
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        owner:
          type: string
      additionalProperties: true
    user:
      type: object
      required:
        - ref
        - owner
        - name
        - email
        - pass
        - role
        - created
      properties:
        ref:
          type: string
        owner:
          type: string
        client:
          type: string
        name:
          type: string
        email:
          type: string
        pass:
          type: string
        role:
          type: string
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        session_private_token:
          type: string
        session_public_token:
          type: string
        session_expiration:
          type: string
          format: date-time
