openapi: 3.0.3
info:
  title: simple-api
  version: 1.0.0
servers:
  - url: 'https'
tags:
  - name: session
  - name: user
  - name: ressource
paths:
  /user:
    parameters:
      - name: client
        in: header
        required: true
        schema:
          type: string
    get:
      tags:
        - user
      responses:
        200:
          description: liste des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
    post:
      tags:
        - user
      responses:
        200:
          description: utilisateur créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
  /user/{ref}:
    parameters:
      - name: client
        in: header
        required: true
        schema:
          type: string
      - name: ref
        in: path
        required: true
        schema: 
          $ref: '#/components/schemas/ref'
    get:
      tags:
        - user
      responses:
        200:
          description: utilisateur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
    post:
      tags:
        - user
      responses:
        200:
          description: utilisateur modifié
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
    delete:
      tags:
        - user
      responses:
        200:
          description: OK, utilisateur supprimé

  /connect:
    parameters:
      - name: client
        in: header
        required: true
        schema:
          type: string
    post:
      tags:
        - session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  format: email
                pass:
                  type: string
                  format: password
      responses:
        200:
          description: sessino connectée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/session'
  /forgotten:
  /recover:
    
  /{ressource}:
    parameters:
      - name: client
        in: header
        required: true
        schema:
          type: string
      - name: ressource
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - ressource
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          schema:
            type: integer
      description: liste les entités de la ressources
      responses:
        200:
          description: liste d'entités
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/entity'
    post:
      tags:
        - ressource
      description: cree une entité de la ressource
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        200:
          description: entité qui vient d'être créée
          content:
            application/json:
              schema:
                $ref: '#components/schemas/entity'
  /{ressource}/{ref}:
    parameters:
      - name: client
        in: header
        required: true
        schema:
          type: string
      - name: ressource
        in: path
        required: true
        schema:
          type: string
      - name: ref
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ref'
    get:
      tags:
        - ressource
      description: entité de la ressources correspondant à la ref
      responses:
        200:
          description: liste d'entités
          content:
            application/json:
              schema:
                $ref: '#components/schemas/entity'
    post:
      tags:
        - ressource
      description: modifie une entité de la ressource correspondant à la ref
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/entity'
      responses:
        200:
          description: entité qui vient d'être modifiée
          content:
            application/json:
              schema:
                $ref: '#components/schemas/entity'
    delete:
      tags:
        - ressource
      description: supprime une entité de la ressource correspondant à la ref
      responses:
        200:
          description: OK, entité supprimée


components:
  schemas:
    ref:
      type: string
      format: uuid
      example: ebe3d81e-c460-424d-8d9d-c6d60f6d0c4b
    token:
      type: string
      example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYmUzZDgxZS1jNDYwLTQyNGQtOGQ5ZC1jNmQ2MGY2ZDBjNGIiLCJuYW1lIjoic3RyaW5nIiwicm9sZSI6InN0cmluZyIsImlhdCI6MTUxNjIzOTAyMiwiZXhwIjoxNjAwMDAwMDAwfQ.9EFQKorBWJpN1_gL0opyy9J87kT8-CaJq2z6OqhJlTM
    entity:
      type: object
      required:
        - ref
        - created
        - owner
      properties:
        ref:
          $ref: '#/components/schemas/ref'
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        owner:
          $ref: '#/components/schemas/ref'
      additionalProperties: true
    user-base:
      type: object
      required:
        - name
        - email
        - role
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
    user-new:
      allOf:
        - $ref: '#/components/schemas/user-base'
        - type: object
          required:
            - pass
            - confirm
          properties:
            pass:
              type: string
              format: password
            confirm:
              type: string
              format: password
    user:
      allOf:
        - $ref: '#/components/schemas/user-base'
        - type: object
          required:
            - ref
            - created
          properties:
            ref:
              $ref: '#/components/schemas/ref'
            created:
              type: string
              format: date-time
            updated:
              type: string
              format: date-time
    session:
      allOf:
        - $ref: '#/components/schemas/user'
        - type: object
          required:
            - session_public_token
            - session_expiration
          properties:
            session_public_token:
              $ref: '#/components/schemas/token'
            session_expiration:
              type: string
              format: date-time



